# Generated by Django 4.0.5 on 2022-06-11 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theawwards', '0007_ratings_content_rate_ratings_design_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ratings',
            name='overall_score',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
