# Generated by Django 4.0.5 on 2022-06-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theawwards', '0008_profile_date_ratings_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='content_avr',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ratings',
            name='design_avr',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ratings',
            name='usability_avr',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
